import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { Download, Eye } from "lucide-react"

export function RecentReports() {
  const recentReports = [
    {
      id: "RPT-001",
      name: "Q1 2024 Sales Report",
      type: "Sales",
      generatedBy: "John Smith",
      date: "2024-03-31",
      status: "Completed",
    },
    {
      id: "RPT-002",
      name: "March Inventory Summary",
      type: "Inventory",
      generatedBy: "Sarah Johnson",
      date: "2024-03-30",
      status: "Completed",
    },
    {
      id: "RPT-003",
      name: "Compliance Certificates Q1",
      type: "Compliance",
      generatedBy: "Mike Davis",
      date: "2024-03-29",
      status: "Completed",
    },
    {
      id: "RPT-004",
      name: "Financial Overview March",
      type: "Financial",
      generatedBy: "Emily Brown",
      date: "2024-03-28",
      status: "Completed",
    },
  ]

  const getTypeColor = (type: string) => {
    switch (type) {
      case "Sales":
        return "bg-blue-100 text-blue-700 hover:bg-blue-100"
      case "Inventory":
        return "bg-green-100 text-green-700 hover:bg-green-100"
      case "Compliance":
        return "bg-purple-100 text-purple-700 hover:bg-purple-100"
      case "Financial":
        return "bg-orange-100 text-orange-700 hover:bg-orange-100"
      default:
        return "bg-gray-100 text-gray-700 hover:bg-gray-100"
    }
  }

  return (
    <Card className="border-0 shadow-md">
      <CardHeader className="border-b bg-gradient-to-r from-blue-50 to-green-50">
        <CardTitle className="text-xl font-semibold">Recent Reports</CardTitle>
      </CardHeader>
      <CardContent className="p-0">
        <Table>
          <TableHeader>
            <TableRow className="bg-muted/50">
              <TableHead className="font-semibold">Report ID</TableHead>
              <TableHead className="font-semibold">Name</TableHead>
              <TableHead className="font-semibold">Type</TableHead>
              <TableHead className="font-semibold">Generated By</TableHead>
              <TableHead className="font-semibold">Date</TableHead>
              <TableHead className="font-semibold">Status</TableHead>
              <TableHead className="text-right font-semibold">Actions</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {recentReports.map((report) => (
              <TableRow key={report.id} className="hover:bg-muted/30">
                <TableCell className="font-medium text-primary">{report.id}</TableCell>
                <TableCell className="font-medium">{report.name}</TableCell>
                <TableCell>
                  <Badge className={getTypeColor(report.type)}>{report.type}</Badge>
                </TableCell>
                <TableCell>{report.generatedBy}</TableCell>
                <TableCell>{report.date}</TableCell>
                <TableCell>
                  <Badge className="bg-green-100 text-green-700 hover:bg-green-100">{report.status}</Badge>
                </TableCell>
                <TableCell className="text-right">
                  <div className="flex justify-end gap-2">
                    <Button variant="ghost" size="icon">
                      <Eye className="h-4 w-4" />
                    </Button>
                    <Button variant="ghost" size="icon">
                      <Download className="h-4 w-4" />
                    </Button>
                  </div>
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </CardContent>
    </Card>
  )
}
